### ISSUE TITLE
404 showcase video

### ISSUE THREAD

**Issue by rpaladin** [pemguin005/Third-Person-Controller---Godot-Souls-like#2]
Link to previous report: <https://github.com/godotengine/godot-asset-library/issues/264>

<hr />

Invalid showcase video: <https://www.youtube.com/GQ96m3ZBLY0>

**Comment by catprisbrey** [comment]
Link tested and works fine. A few models are slightly different since the video was made, but the video is still a valid demonstration of the project.

**Comment by catprisbrey** [comment]
Ah my mistake, i see you now you were meaning the link in the Godot Asset Store is broken. Link updated and submitted to them now. It should update in a  few days.
